import LeanProofs.Basic
import LeanProofs.TaxonomyGraph
import LeanProofs.PersistenceModel
import LeanProofs.BranchSelector
import LeanProofs.RepairOperator
import LeanProofs.OpsMasking
import LeanProofs.Paper24SharedVision
import LeanProofs.Paper25EpistemicBorderControl
import LeanProofs.Admissibility.Authority
import LeanProofs.Admissibility.StateTransition
import LeanProofs.Admissibility.Derivation
import LeanProofs.Admissibility.Execution
import LeanProofs.Admissibility.Corrective
import LeanProofs.Admissibility.CorrectiveBoundary
import LeanProofs.Admissibility.WitnessInvariance
import LeanProofs.Admissibility.FiatAdmissibility
import LeanProofs.Admissibility.NumericalAdmissibility
import LeanProofs.Admissibility.SurfaceAuthorization
import LeanProofs.Admissibility.RecoveryMargin
import LeanProofs.Admissibility.ClosureEligibility
import LeanProofs.Admissibility.ConsolidationDenial
import LeanProofs.Admissibility.DeferredWitness
import LeanProofs.Admissibility.PredicateWitnessSeparation
import LeanProofs.Admissibility.AuthorityScope
import LeanProofs.Admissibility.PublicReceiptRefinement
import LeanProofs.Admissibility.Freshness
import LeanProofs.Admissibility.AxisSkew
import LeanProofs.Admissibility.ReachabilityClosure
import LeanProofs.Admissibility.Composition
import LeanProofs.Admissibility.LocalBoundary
import LeanProofs.Admissibility.CrossBoundaryExposure
import LeanProofs.Admissibility.CrossBoundaryDegradation
import LeanProofs.Admissibility.CrossBoundaryFailureMint
import LeanProofs.Admissibility.CrossBoundaryCascade
import LeanProofs.Admissibility.RefusalPropagation
import LeanProofs.Admissibility.AdmissibilityKernels
import LeanProofs.Admissibility.Examples
import LeanProofs.Admissibility.AuthorizedNotSafe
import LeanProofs.Admissibility.AuthorizedNotSafeWitness
import LeanProofs.Admissibility.SafetyBridge
import LeanProofs.Admissibility.SafetyBridgeWitness
import LeanProofs.Admissibility.AuthorizedStepNotSafe
import LeanProofs.Admissibility.AuthorizedStepNotSafeWitness
import LeanProofs.Admissibility.SafetyTrajectory
import LeanProofs.Admissibility.AttestationLedger
import LeanProofs.CollapsedSurface

-- Witnessed Derivation Calculus (2.0 port; Mathlib-free, see LeanProofs/Witnessed.lean)
import LeanProofs.Witnessed

-- Judgment orientation and exact-origin support (stable, Mathlib-free sibling axis)
import LeanProofs.JudgmentOrientation

-- Reachability/refusal adapters for WDC paid paths (candidate; not public-surface promotion)
import LeanProofs.Admissibility.WitnessedReachability
