/-
  Custody-Class: UNRATIFIED-CANDIDATE

  Admissibility — Axis 2, Slice 2: conflict merge (reconciliation-
  policy failure / degenerate corner).

  Reclassification history:
    - 2026-05-31 a.m.: filed as Slice 0
    - 2026-05-31 p.m.: demoted to "Case B" when SharedBudgetMerge
                       landed as the honest Slice 0
    - 2026-06-01: renumbered as Slice 2 after StaleEvidenceMerge
                  (temporal scope failure) landed as the orthogonal
                  Slice 1

  Why this is Slice 2 rather than one of 0/1: the bad merge here is
  generated by the merge operator's *own policy* (incompatible
  owners → manual `clean := false` flip) rather than by either of
  the two distinct branch-local-scope failures the suite needs:

    - Slice 0 (SharedBudgetMerge): branch-local scope cannot see
      joint resource usage. Failure is spatial/aggregative —
      honest local margins sum past a shared cap.
    - Slice 1 (StaleEvidenceMerge): branch-local scope cannot see
      future time. Failure is temporal — honest local witnesses,
      fresh at action time, are reused at a reconciliation time
      outside their horizon.
    - Slice 2 (this module): the merge operator itself destroys
      value when branch states are incompatible. Degenerate corner;
      preserved as the sibling specimen for merge-policy
      admissibility, not as where `MergeAdmissible`'s
      joint-resource or freshness dimensions earn their existence.

  Keeper result (unchanged): two locally bridged trajectories merge
  into a globally value-losing state. Reading: bridge evidence is
  local to a trajectory; it does not automatically survive
  reconciliation. The missing object (`MergeAdmissible`) is
  deliberately not defined here.

  Maximal bridge: the bridge predicate is exactly value preservation.
  Under this bridge Axis 1's `MaximalBridge` holds — honest about the
  corner. (Slice 1 is the first specimen to use a non-maximal bridge.)

  Scratch annex per the `working/tooltheory/` queue convention. Not on
  the public 1.0 surface. Not root-wired into `LeanProofs.lean`.
  Build with: `lake build LeanProofs.Admissibility.MergeConflict`.
-/

import LeanProofs.Admissibility.SafetyBridge

namespace Admissibility.MergeConflict

open Admissibility.SafetyBridge

/-! ### Local model — owners, states, actions -/

inductive Owner where
  | none
  | alice
  | bob
deriving DecidableEq, Repr

structure MergeState where
  owner : Owner
  clean : Bool
deriving Repr

inductive Act where
  | setOwner (o : Owner) : Act
  | noop : Act

/-- Local transition. `setOwner` rewrites the owner field; `noop`
    leaves the state alone. `clean` is preserved by both. -/
def run : MergeState → Act → MergeState
  | s, .noop => s
  | s, .setOwner o => { s with owner := o }

/-- Defended value: 1 if clean, 0 otherwise. -/
def value (s : MergeState) : Nat :=
  if s.clean then 1 else 0

/-- Maximal bridge (Slice 0 corner case): the bridge is exactly value
    preservation. The Slice 0 point is merge failure, not bridge
    subtlety; a structural bridge over this model would land in a
    later slice. -/
def bridge (s : MergeState) (a : Act) : Prop :=
  value s ≤ value (run s a)

/-- Authorization is unconstrained at Slice 0. The point is
    composition failure under merge, not authorization. -/
def Allowed (_ : MergeState) (_ : Unit) (_ : Act) : Prop := True

/-! ### SafetyEnv instance -/

def mergeEnv : SafetyEnv MergeState Act Unit where
  run := run
  Allowed := Allowed
  value := value
  bridge := bridge
  preserves := fun _ _ h => h

/-! ### Merge operator

  Compatibility: a `none` owner is compatible with anything; equal
  owners are compatible; otherwise incompatible. On a compatible
  merge, the surviving owner is `a.owner` if non-`none`, else
  `b.owner`, and `clean` is the conjunction. On an incompatible
  merge, the result is `{ owner := none, clean := false }` — the
  conflict drops the defended value to 0. -/

def compatibleOwner : Owner → Owner → Bool
  | .none, _ => true
  | _, .none => true
  | .alice, .alice => true
  | .bob, .bob => true
  | _, _ => false

def merge (a b : MergeState) : MergeState :=
  if compatibleOwner a.owner b.owner then
    { owner := if a.owner = Owner.none then b.owner else a.owner
      clean := a.clean && b.clean }
  else
    { owner := .none
      clean := false }

/-! ### The bad-merge witness -/

def s0 : MergeState := { owner := .none, clean := true }
def aliceEnd : MergeState := { owner := .alice, clean := true }
def bobEnd : MergeState := { owner := .bob, clean := true }

/-- The alice hop: from `s0`, set owner to alice. Bridged (clean is
    preserved, value 1 → 1). Authorization is trivial. -/
def aliceHop : SafeStep mergeEnv s0 where
  actor := ()
  act := .setOwner .alice
  allowed := trivial
  bridged :=
    show value s0 ≤ value (run s0 (.setOwner .alice)) by decide

/-- The bob hop: symmetric to the alice hop. -/
def bobHop : SafeStep mergeEnv s0 where
  actor := ()
  act := .setOwner .bob
  allowed := trivial
  bridged :=
    show value s0 ≤ value (run s0 (.setOwner .bob)) by decide

/-- One-hop bridged trajectory for the alice branch. -/
def aliceTraj : BridgedTraj mergeEnv s0 aliceEnd :=
  BridgedTraj.cons aliceHop (BridgedTraj.nil _)

/-- One-hop bridged trajectory for the bob branch. -/
def bobTraj : BridgedTraj mergeEnv s0 bobEnd :=
  BridgedTraj.cons bobHop (BridgedTraj.nil _)

/-- `merge s0 s0` is clean (owners are both `.none`, so compatible
    and the merged result is clean). Value = 1. -/
theorem value_merge_starts : value (merge s0 s0) = 1 := by decide

/-- `merge aliceEnd bobEnd` is not clean (owners are incompatible, so
    the merge falls into the conflict branch). Value = 0. -/
theorem value_merge_ends : value (merge aliceEnd bobEnd) = 0 := by decide

/-- The strict value drop across the merge. -/
theorem merge_value_loss :
    value (merge aliceEnd bobEnd) < value (merge s0 s0) := by decide

/-! ### Axis 2 Slice 0 keeper theorem

  Two locally bridged trajectories whose merged endpoints have
  strictly lower defended value than the merged starting points. The
  witness is `(s0, aliceEnd, s0, bobEnd, aliceTraj, bobTraj,
  merge_value_loss)`. -/

theorem locally_bridged_fragments_can_merge_to_value_loss :
    ∃ (a a' b b' : MergeState)
      (_ : BridgedTraj mergeEnv a a')
      (_ : BridgedTraj mergeEnv b b'),
      value (merge a' b') < value (merge a b) :=
  ⟨s0, aliceEnd, s0, bobEnd, aliceTraj, bobTraj, merge_value_loss⟩

/-! ### Positive object (local): policy-admissibility restores composition

  Slice 2's missing evidence is reconciliation-policy preservation —
  specifically, that the branches' owners are compatible so the merge
  operator does not invoke its conflict branch and manually flip
  `clean := false`. Unlike Slices 0 and 1, the value loss here is *written
  into* `merge`; the admissibility evidence is exactly the condition that
  avoids the policy detonator.

  Three honesty notes for this slice:

  1. The `BridgedTraj` hypotheses are framing, not load-bearing. This
     matches Slices 0 and 1 (under Boolean viability) but is more
     pronounced here: the conclusion follows from
     `conflict_merge_viable_iff_admissible` alone, with no reference to
     the trajectories. They are underscore-bound to mark this.

  2. The iff requires cleanness preconditions (`a.clean = true ∧
     b.clean = true`). The merge's `clean` field is `a.clean && b.clean`
     on the compatible branch, so an unclean input would falsify viability
     regardless of compatibility. Stating the iff *under cleanness*
     isolates the policy-specific dimension cleanly; the cleanness
     precondition is what BridgedTraj would deliver in a non-vacuous
     deployment.

  3. Slice 2 is degenerate but real. Its job is to force the
     policy-preservation dimension of the eventual generic
     `MergeAdmissible`; it is NOT equal-depth to BudgetMerge or
     StaleEvidenceMerge, which exhibit *emergent* composition failure
     under honest merges. -/

@[reducible] def ConflictMergeOk (a b : MergeState) : Prop :=
  compatibleOwner a.owner b.owner = true

/-- Characterization (under cleanness): the merged state is viable iff
    the owners are compatible. The cleanness preconditions are needed
    because the merge's `clean` field on the compatible branch is
    `a.clean && b.clean` — an unclean input would falsify viability
    regardless of owner compatibility, so the iff isolates the
    policy-specific dimension. -/
theorem conflict_merge_viable_iff_admissible
    {a b : MergeState} (ha : a.clean = true) (hb : b.clean = true) :
    value (merge a b) = 1 ↔ ConflictMergeOk a b := by
  unfold value merge ConflictMergeOk
  by_cases hc : compatibleOwner a.owner b.owner = true
  · rw [if_pos hc]
    simp [ha, hb, hc]
  · rw [if_neg hc]
    simp [hc]

/-- Positive restoration for the conflict slice. Given two bridged
    branches with clean endpoints and the policy-compatibility evidence
    `ConflictMergeOk sA sB`, the merged endpoint stays viable — the
    value loss of `locally_bridged_fragments_can_merge_to_value_loss`
    is blocked because the merge does not invoke its conflict branch.

    HONESTY NOTE: the `BridgedTraj` hypotheses are framing, not
    load-bearing. The conclusion follows from
    `conflict_merge_viable_iff_admissible` alone, given cleanness and
    compatibility. Underscore-bound to mark it. -/
theorem conflict_merge_restores
    {s sA sB : MergeState}
    (_tA : BridgedTraj mergeEnv s sA)
    (_tB : BridgedTraj mergeEnv s sB)
    (haClean : sA.clean = true)
    (hbClean : sB.clean = true)
    (ok : ConflictMergeOk sA sB) :
    value (merge sA sB) = 1 :=
  (conflict_merge_viable_iff_admissible haClean hbClean).mpr ok

/-! ### What this slice establishes

  - Each branch is locally bridged. Under the maximal bridge, every
    hop that preserves value qualifies; both `setOwner alice` and
    `setOwner bob` from a clean state preserve the value floor.
  - The merge operator drops the defended value strictly below the
    floor: the merged starts have value 1, the merged ends have
    value 0.
  - Therefore local bridgedness is not compositional across merge
    without extra admissibility evidence.

  Deferred (do not promote until ≥2 more bad-merge specimens land
  per the Axis 2 forcing-case discipline):

    * `MergeAdmissible` positive object. Defining it before the
      bad-case family exists risks a definition that proves itself.
    * Structural (non-maximal) bridge over this or a sibling model.
    * Stale-evidence / time-scoped bridge variant. -/

end Admissibility.MergeConflict
